apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-ingress-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protoc..gr gol: HTTP2  [';/ '
      hosts:./ 
        - "*".
      tls:,.. gpo
        mode: SIMpPLE
–
'/'[–g–≠ÆÚ]æÆ Æ˝Æ¯ ∂®≠ p[ ][][

]
 h| 
]\\[]]}]]]]'\}}\     ,  ,    a
a'